### PR TITLE
C1: QA fixes - 5

### PR DESCRIPTION
**Pull request by ashwin1111**

### CODE REVIEW

**Comment by ashwin1111** [comment]
@coderabbitai review

**Comment by ashwin1111** [comment]
@coderabbitai I haven't requested for any review in the past hour, why am I getting rate limit?

**Comment by ashwin1111** [comment]
@coderabbitai review

**Comment by ashwin1111** [comment]
@coderabbitai review - I've added this twice, why is it not reviewed yet? is it because of large amount of file changes?

**Comment by ashwin1111** [comment]
@coderabbitai it's been 14 hours already

**Review by Shwetabhk — APPROVED** [review]

**Pull request merged**
