### PR TITLE
Fix bugs from testing - QBO

### PR DESCRIPTION
**Pull request by ashwin1111**
## Summary by CodeRabbit

- **New Features**
	- Enhanced form control management with conditional value resets for improved user experience.
	- Export settings now have updated validation and module rules for better accuracy in expense management.
	- Added back navigation functionality in various settings components for easier user navigation through the app.

- **Bug Fixes**
	- Corrected the category mapping behavior to be context-sensitive, ensuring accurate mappings.

- **Refactor**
	- Centralized validator setting/clearing logic for cleaner and more maintainable code.
	- Streamlined export log retrieval with additional parameters for better data filtering.

- **Style**
	- Updated dropdown icons and visibility conditions for a more intuitive and visually consistent user interface.

- **Documentation**
	- Updated storybook with new `ProgressBarModule` to reflect component changes.

### CODE REVIEW

**Comment by ashwin1111** [comment]
@coderabbitai review

**Comment by ashwin1111** [comment]
@coderabbitai generate interesting stats about this repository from git and render them as a table.

**Comment by ashwin1111** [comment]
@coderabbitai create a table with contributor list and number of commits / number of lines

**Comment by ashwin1111** [comment]
> @ashwin1111 Here are the statistics you requested, formatted as a table:
> 
> Contributor	Number of Commits	Number of Lines
> Anish Kumar	956	22293
> Fyle	561	-
> Ashwin T.	410	67236
> Dhaarani	114	21349
> Shwetabh K.	28	160
> Labhvam S.	22	731
> Nilesh P.	18	85
> Ashutosh S.	10	41
> Rushikesh T.	5	43
> Please note that the number of lines for the contributor "Fyle" and some other contributors with fewer commits are not listed, as the output provided did not include them. If you need more detailed information, please let me know.
> 
> Analysis chain
> Scripts executed

can you include only the commits in master @coderabbitai?

**Comment by ashwin1111** [comment]
@coderabbitai can you create a table with an average time taken by the approver to approve a PR after a review is being added.

**Comment by ashwin1111** [comment]
> @ashwin1111 To update the `HRMS` content to `Human Resources Management System` throughout the repository, I will first search for instances of `HRMS` in the codebase. After identifying the files that need to be changed, I will generate a shell script to replace `HRMS` with `Human Resources Management System`. Please confirm that you would like me to proceed with this action and that you are aware of the potential widespread changes this might cause across the repository.

yes, go ahead. Change only the templates and not anything in business logic.

**Comment by ashwin1111** [comment]
> ```shell
> sed -i 's/HRMS/Human Resources Management System/g' ./src/app/integrations/landing/landing.component.html
> ```

@coderabbitai can you create a pull request with the changes?

**Review by Shwetabhk — APPROVED** [review]

**Review by NileshPant1999 — APPROVED** [review]

**Pull request merged**
